#! /bin/sh

bspc config adaptative_raise true
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.05
bspc config focused_border_color "#333333"
bspc config normal_border_color "#000000"
bspc config focus_follows_pointer true

bspc config border_width        2
bspc config window_gap          13
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a Screenkey --unmanage
bspc rule -a Gcolor2 floating=true center=true
bspc rule -a Lxappearance floating=true center=true
bspc rule -a Gmrun floating=true center=true
bspc rule -a Lxterminal floating=true center=true
#bspc rule -a urxvt floating=true center=true
bspc rule -a Viewnior floating=true center=true
bspc rule -a Feh floating=true center=true
bspc rule -a File-roller floating=true center=true
bspc rule -a floaterm floating=true center=true
bspc rule -a xterm floating=true center=true
bspc rule -a bashrun floating=true center=true

#bspc rule -a Firefox desktop=I
#bspc rule -a Calibre desktop=II
#bspc rule -a Geany desktop=II
#bspc rule -a Deluge desktop=III

#bspc monitor -d i ii iii iv v vi vii viii ix x
#bspc monitor -d One Two Three Four Five Six Seven Eight Nine Ten
#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d • • • • • • • • • •


bspc desktop I --layout monocle
bspc desktop II --layout monocle

#compton -b &
#lxpolkit &

#panel

PANEL_HEIGHT=18
PANEL_FIFO="/tmp/panel-fifo"
PANEL_FONT="DejaVu Sans Mono:size=9"

bspc config top_padding $PANEL_HEIGHT

killall bspwmstatus dzen2 bspc xtitle

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &  # Optional: for window title
bspwmstatus | dzen2 -fn "$PANEL_FONT" -h $PANEL_HEIGHT -ta l &

panel dzen2
